#!/usr/bin/env sh

# Run lint-staged to format files
npx lint-staged

# Run React unit tests
npm test

# Run vanilla-renderer unit and export tests
cd vanilla-renderer
npm test
npm run build
npm run test:exports
cd ..
